### ISSUE TITLE
Error on task Configure Tasks

### ISSUE THREAD

**Issue by tekord** [d-language-server/vscode-dlang#12]
Hi! When I run Configure Tasks in the first time I can choose: build, rebuild, run, test. I choose any of these items, run Configure Tasks again, then VSCode goes to infinite searching of available tasks to configure. Console has the following error:

```
workbench.main.js:235 [Extension Host] Trace: BAD uri lacks scheme, falling back to file-scheme.
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:656
	at new f (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:729)
	at new p (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:116:930)
	at Function.parse (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:116:279)
	at module.exports.t.createConverter.e (C:\Users\Cyrill\.vscode-oss\extensions\laurenttreguier.vscode-dls-1.16.4\out\extension.js:1:142344)
	at Object.i [as asUri] (C:\Users\Cyrill\.vscode-oss\extensions\laurenttreguier.vscode-dls-1.16.4\out\extension.js:1:142375)
	at n (C:\Users\Cyrill\.vscode-oss\extensions\laurenttreguier.vscode-dls-1.16.4\out\extension.js:1:154640)
	at module.exports.t.ConfigurationFeature.initialize.e.onRequest (C:\Users\Cyrill\.vscode-oss\extensions\laurenttreguier.vscode-dls-1.16.4\out\extension.js:1:154830)
	at C:\Users\Cyrill\.vscode-oss\extensions\laurenttreguier.vscode-dls-1.16.4\out\extension.js:1:6936
	at C:\Users\Cyrill\.vscode-oss\extensions\laurenttreguier.vscode-dls-1.16.4\out\extension.js:1:7966
	at Immediate.module.exports.C.H.T.size.setImmediate [as _onImmediate] (C:\Users\Cyrill\.vscode-oss\extensions\laurenttreguier.vscode-dls-1.16.4\out\extension.js:1:10396)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5) (at Console.trace (console.js:253:8))
t.log @ workbench.main.js:235
```

**Comment by tekord** [comment]
Also console has the following message:

```
stack trace: Error: Illegal argument: name
	at Object.t.illegalArgument (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:414)
	at t.set name [as name] (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:348:679)
	at new S (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:347:441)
	at new S (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:327:254)
	at module.exports.t.default.provideTasks.filter.map.e (C:\Users\Cyrill\.vscode-oss\extensions\laurenttreguier.vscode-dls-1.16.3\out\extension.js:1:163124)
	at Array.map (<anonymous>)
	at module.exports.t.default.provideTasks (C:\Users\Cyrill\.vscode-oss\extensions\laurenttreguier.vscode-dls-1.16.3\out\extension.js:1:162965)
	at define.$provideTasks.s.asPromise (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:571:937)
	at t.asPromise.Promise (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:49:430)
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:49:402)
	at D.$provideTasks (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:571:912)
	at d._doInvokeHandler (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:622:11)
	at d._invokeHandler (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:716)
	at d._receiveRequest (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:394)
	at d._receiveOneMessage (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:617:400)
	at u.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at e (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:40:460)
	at u.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at a (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:467)
	at e (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:513)
	at u.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at y._receiveMessage (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:415)
	at u.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at f.acceptChunk (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:174:410)
	at Socket.t (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20) (at d.then.t.onMessage.process.on.t.catch.t (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:730:164))
```

**Comment by LaurentTreguier** [comment]
I'm not getting this error using the official VSCode distribution no matter how many times I run "Configure Task", so this looks like a problem from VSCodium (although they don't seem to apply any custom modifications to VSCode).
Does this happen only with vscode-dlang ?

**Comment by tekord** [comment]
@LaurentTreguier Just checked this on the official VSCode 1.32.3 (Portable). Error is there, but it does not affect Task Configuration list generation: https://dl.dropboxusercontent.com/s/zqn6bskjobu1b5z/Code_u59kiuqkf7.png

I believe this error must be terminated and burned in the fire of holy debugger :)

**Comment by LaurentTreguier** [comment]
The reason you have errors is because of how the task is configures. It's a task definition from `code-d`; and `vscode-dlang` doesn't use the same task definitions. It should be something like this instead:
```json
{
    "type": "dub",
    "task": "build",
    "run": false,
    "compiler": "dmd",
    "arch": "x86_64",
    "build": "debug",
    "config": "library",
    "problemMatcher": [
        "$dub-build",
        "$dub-test"
    ]
}
```
